enum FlightPhase
{
  STANDBY = 0,
  LAUNCH  = 1,
  FLIGHT  = 2,
  OFFLINE = 4
};

enum LaunchOrientation
{
  LAUNCHORIENTATION_VERTICAL   = 0,
  LAUNCHORIENTATION_DIAGONAL   = 1,
  LAUNCHORIENTATION_HORIZONTAL = 2
};

enum LaunchMode
{
  LAUNCHMODE_AERODYNAMIC_ONLY,
  LAUNCHMODE_RADIAL_THRUST_SUPPORT,
};

enum WaypointType
{
  WAYPOINTTYPE_EXACT_HIT   = 0,
  WAYPOINTTYPE_APPROXIMATE = 0
};
